clean:
	./gradlew clean
build:
	./gradlew clean build
install:
	./gradlew clean install
test:
	./gradlew test
report:
	cd app && ./gradlew jacocoTestReport
lint:
	./gradlew checkstyleMain
.PHONY: build